# Generated by Django 4.0.6 on 2022-09-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_service', models.CharField(choices=[('w', 'web design'), ('v', 'video editing'), ('p', 'photo editing'), ('u', 'ui ux design'), ('s', '-select-')], default='s', max_length=1)),
                ('your_name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
    ]
