# Generated by Django 4.0.6 on 2022-09-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addservice',
            name='select_service',
            field=models.CharField(choices=[('web design', 'w'), ('video editing', 'v'), ('photo editing', 'p'), ('ui ux design', 'u'), ('-select-', 's')], default='s', max_length=100),
        ),
    ]
