# Generated by Django 4.0.6 on 2022-09-14 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socio_app', '0002_alter_addservice_select_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addservice',
            old_name='your_name',
            new_name='username',
        ),
    ]
