# Generated by Django 4.0.6 on 2022-09-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio_app', '0003_rename_your_name_addservice_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addservice',
            old_name='username',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='addservice',
            name='select_service',
        ),
        migrations.AddField(
            model_name='addservice',
            name='category',
            field=models.CharField(choices=[('Web Design', 'Web Design'), ('Video Editing', 'Video Editing'), ('Photo Editing', 'Photo Editing'), ('IT Service', 'IT Service'), ('UI/UX Design', 'UI/UX Design'), ('Accountancy & Taxes', 'Accountancy & Taxes')], default='Web Design', max_length=50),
        ),
        migrations.AlterField(
            model_name='addservice',
            name='price',
            field=models.CharField(max_length=200),
        ),
    ]
