# Generated by Django 4.0.6 on 2022-09-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio_app', '0004_rename_username_addservice_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=50)),
                ('category', models.CharField(choices=[('Web Design', 'Web Design'), ('Video Editing', 'Video Editing'), ('Photo Editing', 'Photo Editing'), ('IT Service', 'IT Service'), ('UI/UX Design', 'UI/UX Design'), ('Accountancy & Taxes', 'Accountancy & Taxes')], default='Web Design', max_length=50)),
            ],
        ),
    ]
