# Generated by Django 4.0.6 on 2022-09-15 18:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socio_app', '0005_queries'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
