# Generated by Django 4.0.6 on 2022-09-15 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socio_app', '0006_queries_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='create_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
