# Generated by Django 4.0.6 on 2022-09-19 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socio_app', '0014_answers_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='answer',
            new_name='questions',
        ),
    ]
