# Generated by Django 4.0.6 on 2022-09-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio_app', '0016_answers_user_alter_answers_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='quest_detail',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='queries',
            name='question',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
