# Generated by Django 4.0.6 on 2022-09-19 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socio_app', '0017_queries_quest_detail_alter_queries_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queries',
            old_name='quest_detail',
            new_name='question_detail',
        ),
    ]
