# Generated by Django 4.0.6 on 2022-09-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio_app', '0018_rename_quest_detail_queries_question_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='question',
            field=models.CharField(default='No Details', max_length=50),
        ),
    ]
