# Generated by Django 4.0.6 on 2022-09-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio_app', '0019_alter_queries_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='question',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='queries',
            name='question_detail',
            field=models.TextField(default='No Details', max_length=200),
        ),
    ]
