# Generated by Django 4.0.6 on 2022-09-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio_app', '0021_queries_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='detail',
            field=models.TextField(default='No Answers', max_length=200, null=True),
        ),
    ]
