# Generated by Django 4.0.6 on 2022-09-19 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socio_app', '0022_alter_answers_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='detail',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='user',
            field=models.ForeignKey(default='anonymous user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
