# Generated by Django 4.0.6 on 2022-09-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socio_app', '0024_alter_answers_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='detail',
            new_name='answer',
        ),
    ]
