# Generated by Django 4.0.6 on 2022-09-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio_app', '0026_rename_answer_answers_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='detail',
            field=models.TextField(default='Write Your Answer Here', max_length=200),
        ),
    ]
