# Generated by Django 4.0.6 on 2022-09-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio_app', '0027_alter_answers_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='addservice',
            name='detail',
            field=models.TextField(default='No Details', max_length=200),
        ),
    ]
